apiVersion: lifecycle.ai-infra.demo/v1alpha1
kind: WorkloadLifecycle
metadata:
  labels:
    app.kubernetes.io/name: go-operator
    app.kubernetes.io/managed-by: kustomize
  name: workloadlifecycle-sample
spec:
  targetDeployment: mock-vllm
  metricsEndpoint: http://localhost:8080/metrics
  kvCacheThresholdPercent: 80
  kvCacheScaleDownThresholdPercent: 25
  minReplicas: 1
  maxReplicas: 3