[controller]
node1 ansible_host=89.169.113.35

[compute]
node2 ansible_host=89.169.123.255

[all:vars]
ansible_user=user
ansible_ssh_private_key_file=credentials/private.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
