{
 "title": "jimmy-vllm-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"default/vllm\"} |= `ERROR`"
    },
    {
     "direction": "backward",
     "expr": "{job=\"default/vllm\"} |= ``"
    }
   ]
  },
  {
   "title": "KV Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "vllm:kv_cache_usage_perc", "legendFormat": "kv_cache_usage_percentage" },
    {
     "expr": "vllm:prefix_cache_queries_total",
     "legendFormat": "prefix_cache_queries_total"
    },
    { "expr": "vllm:prefix_cache_hits_total", "legendFormat": "prefix_cache_hits" }
   ]
  },
  {
   "title": "Request Pipeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "vllm:num_requests_running", "legendFormat": "num_request_running" },
    { "expr": "vllm:num_requests_waiting", "legendFormat": "num_requests_waiting" }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(vllm:time_to_first_token_seconds_bucket[5m]))",
     "legendFormat": "TTFT_p95"
    },
    {
     "expr": "histogram_quantile(0.5, rate(vllm:time_to_first_token_seconds_bucket[5m]))",
     "legendFormat": "TTFT_p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(vllm:request_time_per_output_token_seconds_bucket[5m]))",
     "legendFormat": "TPOT_p95"
    },
    {
     "expr": "histogram_quantile(0.50, rate(vllm:request_time_per_output_token_seconds_bucket[5m]))",
     "legendFormat": "TPOT_p50"
    }
   ]
  }
 ]
}